#include "glprocs.h"

PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB = nullptr;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays = nullptr;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray = nullptr;
PFNGLGENBUFFERSPROC glGenBuffers = nullptr;
PFNGLBINDBUFFERPROC glBindBuffer = nullptr;
PFNGLBUFFERDATAPROC glBufferData = nullptr;
PFNGLCREATESHADERPROC glCreateShader = nullptr;
PFNGLDELETESHADERPROC glDeleteShader = nullptr;
PFNGLSHADERSOURCEPROC glShaderSource = nullptr;
PFNGLCOMPILESHADERPROC glCompileShader = nullptr;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog = nullptr;
PFNGLGETSHADERIVPROC glGetShaderiv = nullptr;
PFNGLCREATEPROGRAMPROC glCreateProgram = nullptr;
PFNGLDELETEPROGRAMPROC glDeleteProgram = nullptr;
PFNGLATTACHSHADERPROC glAttachShader = nullptr;
PFNGLLINKPROGRAMPROC glLinkProgram = nullptr;
PFNGLUSEPROGRAMPROC glUseProgram = nullptr;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog = nullptr;
PFNGLGETPROGRAMIVPROC glGetProgramiv = nullptr;
PFNGLUNIFORM1FPROC glUniform1f = nullptr;
PFNGLUNIFORM1IPROC glUniform1i = nullptr;
PFNGLUNIFORM3FVPROC glUniform3fv = nullptr;
PFNGLUNIFORM4FVPROC glUniform4fv = nullptr;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv = nullptr;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation = nullptr;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer = nullptr;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = nullptr;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = nullptr;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation = nullptr;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation = nullptr;
PFNGLBLENDEQUATIONPROC glBlendEquation = nullptr;

#define VALIDGLPROC(type, name) if (! (GLPROC (type, name))) return false;

bool glprocs ()
{
  VALIDGLPROC (PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
  VALIDGLPROC (PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
  VALIDGLPROC (PFNGLGENBUFFERSPROC, glGenBuffers);
  VALIDGLPROC (PFNGLBINDBUFFERPROC, glBindBuffer);
  VALIDGLPROC (PFNGLBUFFERDATAPROC, glBufferData);
  VALIDGLPROC (PFNGLCREATESHADERPROC, glCreateShader);
  VALIDGLPROC (PFNGLDELETESHADERPROC, glDeleteShader);
  VALIDGLPROC (PFNGLSHADERSOURCEPROC, glShaderSource);
  VALIDGLPROC (PFNGLCOMPILESHADERPROC, glCompileShader);
  VALIDGLPROC (PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
  VALIDGLPROC (PFNGLGETSHADERIVPROC, glGetShaderiv);
  VALIDGLPROC (PFNGLCREATEPROGRAMPROC, glCreateProgram);
  VALIDGLPROC (PFNGLDELETEPROGRAMPROC, glDeleteProgram);
  VALIDGLPROC (PFNGLATTACHSHADERPROC, glAttachShader);
  VALIDGLPROC (PFNGLLINKPROGRAMPROC, glLinkProgram);
  VALIDGLPROC (PFNGLUSEPROGRAMPROC, glUseProgram);
  VALIDGLPROC (PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
  VALIDGLPROC (PFNGLGETPROGRAMIVPROC, glGetProgramiv);
  VALIDGLPROC (PFNGLUNIFORM1FPROC, glUniform1f);
  VALIDGLPROC (PFNGLUNIFORM1IPROC, glUniform1i);
  VALIDGLPROC (PFNGLUNIFORM3FVPROC, glUniform3fv);
  VALIDGLPROC (PFNGLUNIFORM4FVPROC, glUniform4fv);
  VALIDGLPROC (PFNGLUNIFORMMATRIX4FVPROC, glUniformMatrix4fv);
  VALIDGLPROC (PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
  VALIDGLPROC (PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
  VALIDGLPROC (PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
  VALIDGLPROC (PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray);
  VALIDGLPROC (PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation);
  VALIDGLPROC (PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation);
  VALIDGLPROC (PFNGLBLENDEQUATIONPROC, glBlendEquation);

  return true;
}

